version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: sgetjmt
      ME_CONFIG_BASICAUTH_PASSWORD: SGEExpress2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: SGEMongo2019!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SGEMongo2019!
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo

  server:
    container_name: SGE-API
    restart: always
    build:
      context: ./SGE-API/
    ports:
      - '5000:80'
    links:
      - mongo

  client:
    container_name: SGE-UI
    build:
      context: ./SGE-UI/
    volumes:
      - ./SGE-UI/:/usr/app
      - /usr/app/node_modules
    ports:
      - '80:80'
    links:
      - server

networks: 
  mongo-compose-network:
    driver: bridge