version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    command: mongod --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
  server:
    container_name: SGE-API
    restart: always
    build:
      context: ./SGE-API/
    ports:
      - '5000:5000'
    volumes:
      - ./SGE-API/:/usr/app
      - /usr/app/node_modules
    links:
      - mongodb
  client:
    container_name: SGE-UI
    build:
      context: ./SGE-UI/
    volumes:
      - ./SGE-UI/:/usr/app
      - /usr/app/node_modules
    ports:
      - '80:80'
    links:
      - SGE-API